### ISSUE TITLE
Missing casting from LiveEvent

### ISSUE THREAD

**Issue by SamYStudiO** [hadilq/LiveEvent#36]
https://github.com/hadilq/LiveEvent/blob/027ac57d093c9b8f9fddeb3ef8517de2b8b65534/lib/src/main/java/com/hadilq/liveevent/LiveEvent.kt#L44

Shouldn't this line be 
`if (observer is ObserverWrapper && observers.remove(observer)) {`
Got lint error here

**Comment by hadilq** [comment]
Thanks @SamYStudiO for your suggestion.

I am running `./gradlew check` to see the lint report in `lint-results.html` file, but there's no such error! What is the version of gradle you are using?

However, I don't get why lint should give an error on this! If `observer` is not an instance of `ObserverWrapper` then it would not get removed, because `observers` could not hold it in the first place! Can you explain a possible flaw there? Thanks!

**Comment by SamYStudiO** [comment]
![screen](https://user-images.githubusercontent.com/3678076/114572397-bb290100-9c77-11eb-9bfd-5fbfdc7f8869.png)

Here the lint error
gradle 6.5
AS 4.1.3
For me this lint error make sense since this is an array of ObserverWrapper and there is no variance

**Comment by hadilq** [comment]
Thanks @SamYStudiO I am updating the versions, so probably see the lint error soon :D 

Also I'll fix it anyway and publish an update today, if everything goes well.
